# Generated by Django 4.2.4 on 2023-10-05 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ayat",
            old_name="surah",
            new_name="surah_id",
        ),
    ]
