# Generated by Django 4.2.4 on 2023-10-05 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0002_rename_surah_ayat_surah_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ayat",
            old_name="surah_id",
            new_name="surah",
        ),
    ]
